// Objective-C API for talking to github.com/sagernet/sing-box/experimental/libtech Go package.
//   gobind -lang=objc github.com/sagernet/sing-box/experimental/libtech
//
// File is generated by gobind. Do not edit.

#ifndef __Libtech_H__
#define __Libtech_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class LibtechBoxService;
@class LibtechCommandClient;
@class LibtechCommandClientOptions;
@class LibtechCommandServer;
@class LibtechConnection;
@class LibtechConnections;
@class LibtechDeprecatedNote;
@class LibtechErrorMessage;
@class LibtechExchangeContext;
@class LibtechImportRemoteProfile;
@class LibtechNetworkInterface;
@class LibtechNotification;
@class LibtechOutboundGroup;
@class LibtechOutboundGroupItem;
@class LibtechPProfServer;
@class LibtechProfileContent;
@class LibtechProfileContentRequest;
@class LibtechProfileDecoder;
@class LibtechProfileEncoder;
@class LibtechProfilePreview;
@class LibtechRoutePrefix;
@class LibtechSetupOptions;
@class LibtechStatusMessage;
@class LibtechStringBox;
@class LibtechSystemProxyStatus;
@class LibtechWIFIState;
@protocol LibtechCommandClientHandler;
@class LibtechCommandClientHandler;
@protocol LibtechCommandServerHandler;
@class LibtechCommandServerHandler;
@protocol LibtechConnectionIterator;
@class LibtechConnectionIterator;
@protocol LibtechDeprecatedNoteIterator;
@class LibtechDeprecatedNoteIterator;
@protocol LibtechFunc;
@class LibtechFunc;
@protocol LibtechHTTPClient;
@class LibtechHTTPClient;
@protocol LibtechHTTPRequest;
@class LibtechHTTPRequest;
@protocol LibtechHTTPResponse;
@class LibtechHTTPResponse;
@protocol LibtechInterfaceUpdateListener;
@class LibtechInterfaceUpdateListener;
@protocol LibtechLocalDNSTransport;
@class LibtechLocalDNSTransport;
@protocol LibtechNetworkInterfaceIterator;
@class LibtechNetworkInterfaceIterator;
@protocol LibtechOnDemandRule;
@class LibtechOnDemandRule;
@protocol LibtechOnDemandRuleIterator;
@class LibtechOnDemandRuleIterator;
@protocol LibtechOutboundGroupItemIterator;
@class LibtechOutboundGroupItemIterator;
@protocol LibtechOutboundGroupIterator;
@class LibtechOutboundGroupIterator;
@protocol LibtechPlatformInterface;
@class LibtechPlatformInterface;
@protocol LibtechProfilePreviewIterator;
@class LibtechProfilePreviewIterator;
@protocol LibtechRoutePrefixIterator;
@class LibtechRoutePrefixIterator;
@protocol LibtechStringIterator;
@class LibtechStringIterator;
@protocol LibtechTunInterface;
@class LibtechTunInterface;
@protocol LibtechTunOptions;
@class LibtechTunOptions;

@protocol LibtechCommandClientHandler <NSObject>
- (void)clearLogs;
- (void)connected;
- (void)disconnected:(NSString* _Nullable)message;
- (void)initializeClashMode:(id<LibtechStringIterator> _Nullable)modeList currentMode:(NSString* _Nullable)currentMode;
- (void)updateClashMode:(NSString* _Nullable)newMode;
- (void)writeConnections:(LibtechConnections* _Nullable)message;
- (void)writeGroups:(id<LibtechOutboundGroupIterator> _Nullable)message;
- (void)writeLogs:(id<LibtechStringIterator> _Nullable)messageList;
- (void)writeStatus:(LibtechStatusMessage* _Nullable)message;
@end

@protocol LibtechCommandServerHandler <NSObject>
- (LibtechSystemProxyStatus* _Nullable)getSystemProxyStatus;
- (void)postServiceClose;
- (BOOL)serviceReload:(NSError* _Nullable* _Nullable)error;
- (BOOL)setSystemProxyEnabled:(BOOL)isEnabled error:(NSError* _Nullable* _Nullable)error;
@end

@protocol LibtechConnectionIterator <NSObject>
- (BOOL)hasNext;
- (LibtechConnection* _Nullable)next;
@end

@protocol LibtechDeprecatedNoteIterator <NSObject>
- (BOOL)hasNext;
- (LibtechDeprecatedNote* _Nullable)next;
@end

@protocol LibtechFunc <NSObject>
- (BOOL)invoke:(NSError* _Nullable* _Nullable)error;
@end

@protocol LibtechHTTPClient <NSObject>
- (void)close;
- (void)keepAlive;
- (void)modernTLS;
- (id<LibtechHTTPRequest> _Nullable)newRequest;
- (void)pinnedSHA256:(NSString* _Nullable)sumHex;
- (void)pinnedTLS12;
- (void)restrictedTLS;
- (void)trySocks5:(int32_t)port;
@end

@protocol LibtechHTTPRequest <NSObject>
- (id<LibtechHTTPResponse> _Nullable)execute:(NSError* _Nullable* _Nullable)error;
- (void)randomUserAgent;
- (void)setContent:(NSData* _Nullable)content;
- (void)setContentString:(NSString* _Nullable)content;
- (void)setHeader:(NSString* _Nullable)key value:(NSString* _Nullable)value;
- (void)setMethod:(NSString* _Nullable)method;
- (BOOL)setURL:(NSString* _Nullable)link error:(NSError* _Nullable* _Nullable)error;
- (void)setUserAgent:(NSString* _Nullable)userAgent;
@end

@protocol LibtechHTTPResponse <NSObject>
- (LibtechStringBox* _Nullable)getContent:(NSError* _Nullable* _Nullable)error;
- (BOOL)writeTo:(NSString* _Nullable)path error:(NSError* _Nullable* _Nullable)error;
@end

@protocol LibtechInterfaceUpdateListener <NSObject>
- (void)updateDefaultInterface:(NSString* _Nullable)interfaceName interfaceIndex:(int32_t)interfaceIndex isExpensive:(BOOL)isExpensive isConstrained:(BOOL)isConstrained;
@end

@protocol LibtechLocalDNSTransport <NSObject>
- (BOOL)exchange:(LibtechExchangeContext* _Nullable)ctx message:(NSData* _Nullable)message error:(NSError* _Nullable* _Nullable)error;
- (BOOL)lookup:(LibtechExchangeContext* _Nullable)ctx network:(NSString* _Nullable)network domain:(NSString* _Nullable)domain error:(NSError* _Nullable* _Nullable)error;
- (BOOL)raw;
@end

@protocol LibtechNetworkInterfaceIterator <NSObject>
- (BOOL)hasNext;
- (LibtechNetworkInterface* _Nullable)next;
@end

@protocol LibtechOnDemandRule <NSObject>
- (id<LibtechStringIterator> _Nullable)dnsSearchDomainMatch;
- (id<LibtechStringIterator> _Nullable)dnsServerAddressMatch;
- (int32_t)interfaceTypeMatch;
- (NSString* _Nonnull)probeURL;
- (id<LibtechStringIterator> _Nullable)ssidMatch;
- (int32_t)target;
@end

@protocol LibtechOnDemandRuleIterator <NSObject>
- (BOOL)hasNext;
- (id<LibtechOnDemandRule> _Nullable)next;
@end

@protocol LibtechOutboundGroupItemIterator <NSObject>
- (BOOL)hasNext;
- (LibtechOutboundGroupItem* _Nullable)next;
@end

@protocol LibtechOutboundGroupIterator <NSObject>
- (BOOL)hasNext;
- (LibtechOutboundGroup* _Nullable)next;
@end

@protocol LibtechPlatformInterface <NSObject>
- (BOOL)autoDetectInterfaceControl:(int32_t)fd error:(NSError* _Nullable* _Nullable)error;
- (void)clearDNSCache;
- (BOOL)closeDefaultInterfaceMonitor:(id<LibtechInterfaceUpdateListener> _Nullable)listener error:(NSError* _Nullable* _Nullable)error;
- (BOOL)findConnectionOwner:(int32_t)ipProtocol sourceAddress:(NSString* _Nullable)sourceAddress sourcePort:(int32_t)sourcePort destinationAddress:(NSString* _Nullable)destinationAddress destinationPort:(int32_t)destinationPort ret0_:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (id<LibtechNetworkInterfaceIterator> _Nullable)getInterfaces:(NSError* _Nullable* _Nullable)error;
- (BOOL)includeAllNetworks;
- (BOOL)openTun:(id<LibtechTunOptions> _Nullable)options ret0_:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)packageNameByUid:(int32_t)uid error:(NSError* _Nullable* _Nullable)error;
- (LibtechWIFIState* _Nullable)readWIFIState;
- (BOOL)sendNotification:(LibtechNotification* _Nullable)notification error:(NSError* _Nullable* _Nullable)error;
- (BOOL)startDefaultInterfaceMonitor:(id<LibtechInterfaceUpdateListener> _Nullable)listener error:(NSError* _Nullable* _Nullable)error;
- (BOOL)uidByPackageName:(NSString* _Nullable)packageName ret0_:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (BOOL)underNetworkExtension;
- (BOOL)usePlatformAutoDetectInterfaceControl;
- (BOOL)useProcFS;
- (void)writeLog:(NSString* _Nullable)message;
@end

@protocol LibtechProfilePreviewIterator <NSObject>
- (BOOL)hasNext;
- (LibtechProfilePreview* _Nullable)next;
@end

@protocol LibtechRoutePrefixIterator <NSObject>
- (BOOL)hasNext;
- (LibtechRoutePrefix* _Nullable)next;
@end

@protocol LibtechStringIterator <NSObject>
- (BOOL)hasNext;
- (int32_t)len;
- (NSString* _Nonnull)next;
@end

@protocol LibtechTunInterface <NSObject>
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (int32_t)fileDescriptor;
@end

@protocol LibtechTunOptions <NSObject>
- (BOOL)getAutoRoute;
- (LibtechStringBox* _Nullable)getDNSServerAddress:(NSError* _Nullable* _Nullable)error;
- (id<LibtechStringIterator> _Nullable)getExcludePackage;
- (id<LibtechStringIterator> _Nullable)getHTTPProxyBypassDomain;
- (id<LibtechStringIterator> _Nullable)getHTTPProxyMatchDomain;
- (NSString* _Nonnull)getHTTPProxyServer;
- (int32_t)getHTTPProxyServerPort;
- (id<LibtechStringIterator> _Nullable)getIncludePackage;
- (id<LibtechRoutePrefixIterator> _Nullable)getInet4Address;
- (id<LibtechRoutePrefixIterator> _Nullable)getInet4RouteAddress;
- (id<LibtechRoutePrefixIterator> _Nullable)getInet4RouteExcludeAddress;
- (id<LibtechRoutePrefixIterator> _Nullable)getInet4RouteRange;
- (id<LibtechRoutePrefixIterator> _Nullable)getInet6Address;
- (id<LibtechRoutePrefixIterator> _Nullable)getInet6RouteAddress;
- (id<LibtechRoutePrefixIterator> _Nullable)getInet6RouteExcludeAddress;
- (id<LibtechRoutePrefixIterator> _Nullable)getInet6RouteRange;
- (int32_t)getMTU;
- (BOOL)getStrictRoute;
- (BOOL)isHTTPProxyEnabled;
@end

@interface LibtechBoxService : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (BOOL)needWIFIState;
- (void)pause;
- (void)resetNetwork;
- (BOOL)start:(NSError* _Nullable* _Nullable)error;
- (void)updateWIFIState;
- (void)wake;
@end

@interface LibtechCommandClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(id<LibtechCommandClientHandler> _Nullable)handler options:(LibtechCommandClientOptions* _Nullable)options;
- (BOOL)closeConnection:(NSString* _Nullable)connId error:(NSError* _Nullable* _Nullable)error;
- (BOOL)closeConnections:(NSError* _Nullable* _Nullable)error;
- (BOOL)connect:(NSError* _Nullable* _Nullable)error;
- (BOOL)disconnect:(NSError* _Nullable* _Nullable)error;
- (id<LibtechDeprecatedNoteIterator> _Nullable)getDeprecatedNotes:(NSError* _Nullable* _Nullable)error;
- (LibtechSystemProxyStatus* _Nullable)getSystemProxyStatus:(NSError* _Nullable* _Nullable)error;
- (BOOL)selectOutbound:(NSString* _Nullable)groupTag outboundTag:(NSString* _Nullable)outboundTag error:(NSError* _Nullable* _Nullable)error;
- (BOOL)serviceClose:(NSError* _Nullable* _Nullable)error;
- (BOOL)serviceReload:(NSError* _Nullable* _Nullable)error;
- (BOOL)setClashMode:(NSString* _Nullable)newMode error:(NSError* _Nullable* _Nullable)error;
- (BOOL)setGroupExpand:(NSString* _Nullable)groupTag isExpand:(BOOL)isExpand error:(NSError* _Nullable* _Nullable)error;
- (BOOL)setSystemProxyEnabled:(BOOL)isEnabled error:(NSError* _Nullable* _Nullable)error;
- (BOOL)urlTest:(NSString* _Nullable)groupTag error:(NSError* _Nullable* _Nullable)error;
@end

@interface LibtechCommandClientOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int32_t command;
@property (nonatomic) int64_t statusInterval;
@end

@interface LibtechCommandServer : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(id<LibtechCommandServerHandler> _Nullable)handler maxLines:(int32_t)maxLines;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (void)resetLog;
- (void)setService:(LibtechBoxService* _Nullable)newService;
- (BOOL)start:(NSError* _Nullable* _Nullable)error;
- (void)writeMessage:(NSString* _Nullable)message;
@end

@interface LibtechConnection : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull id_;
@property (nonatomic) NSString* _Nonnull inbound;
@property (nonatomic) NSString* _Nonnull inboundType;
@property (nonatomic) int32_t ipVersion;
@property (nonatomic) NSString* _Nonnull network;
@property (nonatomic) NSString* _Nonnull source;
@property (nonatomic) NSString* _Nonnull destination;
@property (nonatomic) NSString* _Nonnull domain;
@property (nonatomic) NSString* _Nonnull protocol;
@property (nonatomic) NSString* _Nonnull user;
@property (nonatomic) NSString* _Nonnull fromOutbound;
@property (nonatomic) int64_t createdAt;
@property (nonatomic) int64_t closedAt;
@property (nonatomic) int64_t uplink;
@property (nonatomic) int64_t downlink;
@property (nonatomic) int64_t uplinkTotal;
@property (nonatomic) int64_t downlinkTotal;
@property (nonatomic) NSString* _Nonnull rule;
@property (nonatomic) NSString* _Nonnull outbound;
@property (nonatomic) NSString* _Nonnull outboundType;
// skipped field Connection.ChainList with unsupported type: []string

- (id<LibtechStringIterator> _Nullable)chain;
- (NSString* _Nonnull)displayDestination;
@end

@interface LibtechConnections : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (void)filterState:(int32_t)state;
- (id<LibtechConnectionIterator> _Nullable)iterator;
- (void)sortByDate;
- (void)sortByTraffic;
- (void)sortByTrafficTotal;
@end

@interface LibtechDeprecatedNote : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull name;
@property (nonatomic) NSString* _Nonnull description;
@property (nonatomic) NSString* _Nonnull deprecatedVersion;
@property (nonatomic) NSString* _Nonnull scheduledVersion;
@property (nonatomic) NSString* _Nonnull envName;
@property (nonatomic) NSString* _Nonnull migrationLink;
- (BOOL)impending;
- (NSString* _Nonnull)message;
- (NSString* _Nonnull)messageWithLink;
@end

@interface LibtechErrorMessage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull message;
- (NSData* _Nullable)encode;
@end

@interface LibtechExchangeContext : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (void)errnoCode:(int32_t)code;
- (void)errorCode:(int32_t)code;
- (void)onCancel:(id<LibtechFunc> _Nullable)callback;
- (void)rawSuccess:(NSData* _Nullable)result;
- (void)success:(NSString* _Nullable)result;
@end

@interface LibtechImportRemoteProfile : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull name;
@property (nonatomic) NSString* _Nonnull url;
@property (nonatomic) NSString* _Nonnull host;
@end

@interface LibtechNetworkInterface : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int32_t index;
@property (nonatomic) int32_t mtu;
@property (nonatomic) NSString* _Nonnull name;
@property (nonatomic) id<LibtechStringIterator> _Nullable addresses;
@property (nonatomic) int32_t flags;
@property (nonatomic) int32_t type;
@property (nonatomic) id<LibtechStringIterator> _Nullable dnsServer;
@property (nonatomic) BOOL metered;
@end

@interface LibtechNotification : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull identifier;
@property (nonatomic) NSString* _Nonnull typeName;
@property (nonatomic) int32_t typeID;
@property (nonatomic) NSString* _Nonnull title;
@property (nonatomic) NSString* _Nonnull subtitle;
@property (nonatomic) NSString* _Nonnull body;
@property (nonatomic) NSString* _Nonnull openURL;
@end

@interface LibtechOutboundGroup : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull tag;
@property (nonatomic) NSString* _Nonnull type;
@property (nonatomic) BOOL selectable;
@property (nonatomic) NSString* _Nonnull selected;
@property (nonatomic) BOOL isExpand;
// skipped field OutboundGroup.ItemList with unsupported type: []*github.com/sagernet/sing-box/experimental/libtech.OutboundGroupItem

- (id<LibtechOutboundGroupItemIterator> _Nullable)getItems;
@end

@interface LibtechOutboundGroupItem : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull tag;
@property (nonatomic) NSString* _Nonnull type;
@property (nonatomic) int64_t urlTestTime;
@property (nonatomic) int32_t urlTestDelay;
@end

@interface LibtechPProfServer : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(long)port;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (BOOL)start:(NSError* _Nullable* _Nullable)error;
@end

@interface LibtechProfileContent : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull name;
@property (nonatomic) int32_t type;
@property (nonatomic) NSString* _Nonnull config;
@property (nonatomic) NSString* _Nonnull remotePath;
@property (nonatomic) BOOL autoUpdate;
@property (nonatomic) int32_t autoUpdateInterval;
@property (nonatomic) int64_t lastUpdated;
- (NSData* _Nullable)encode;
@end

@interface LibtechProfileContentRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t profileID;
- (NSData* _Nullable)encode;
@end

@interface LibtechProfileDecoder : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)decode:(NSData* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
- (id<LibtechProfilePreviewIterator> _Nullable)iterator;
@end

@interface LibtechProfileEncoder : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (void)append:(LibtechProfilePreview* _Nullable)profile;
- (NSData* _Nullable)encode;
@end

@interface LibtechProfilePreview : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t profileID;
@property (nonatomic) NSString* _Nonnull name;
@property (nonatomic) int32_t type;
@end

@interface LibtechRoutePrefix : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSString* _Nonnull)address;
- (NSString* _Nonnull)mask;
- (int32_t)prefix;
- (NSString* _Nonnull)string;
@end

@interface LibtechSetupOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull basePath;
@property (nonatomic) NSString* _Nonnull workingPath;
@property (nonatomic) NSString* _Nonnull tempPath;
@property (nonatomic) NSString* _Nonnull username;
@property (nonatomic) BOOL isTVOS;
@property (nonatomic) BOOL fixAndroidStack;
@end

@interface LibtechStatusMessage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t memory;
@property (nonatomic) int32_t goroutines;
@property (nonatomic) int32_t connectionsIn;
@property (nonatomic) int32_t connectionsOut;
@property (nonatomic) BOOL trafficAvailable;
@property (nonatomic) int64_t uplink;
@property (nonatomic) int64_t downlink;
@property (nonatomic) int64_t uplinkTotal;
@property (nonatomic) int64_t downlinkTotal;
@end

@interface LibtechStringBox : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull value;
@end

@interface LibtechSystemProxyStatus : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) BOOL available;
@property (nonatomic) BOOL enabled;
@end

@interface LibtechWIFIState : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)wifiSSID wifiBSSID:(NSString* _Nullable)wifiBSSID;
@property (nonatomic) NSString* _Nonnull ssid;
@property (nonatomic) NSString* _Nonnull bssid;
@end

FOUNDATION_EXPORT const int32_t LibtechCommandClashMode;
FOUNDATION_EXPORT const int32_t LibtechCommandCloseConnection;
FOUNDATION_EXPORT const int32_t LibtechCommandCloseConnections;
FOUNDATION_EXPORT const int32_t LibtechCommandConnections;
FOUNDATION_EXPORT const int32_t LibtechCommandGetDeprecatedNotes;
FOUNDATION_EXPORT const int32_t LibtechCommandGetSystemProxyStatus;
FOUNDATION_EXPORT const int32_t LibtechCommandGroup;
FOUNDATION_EXPORT const int32_t LibtechCommandGroupExpand;
FOUNDATION_EXPORT const int32_t LibtechCommandLog;
FOUNDATION_EXPORT const int32_t LibtechCommandSelectOutbound;
FOUNDATION_EXPORT const int32_t LibtechCommandServiceClose;
FOUNDATION_EXPORT const int32_t LibtechCommandServiceReload;
FOUNDATION_EXPORT const int32_t LibtechCommandSetClashMode;
FOUNDATION_EXPORT const int32_t LibtechCommandSetSystemProxyEnabled;
FOUNDATION_EXPORT const int32_t LibtechCommandStatus;
FOUNDATION_EXPORT const int32_t LibtechCommandURLTest;
FOUNDATION_EXPORT const int64_t LibtechConnectionStateActive;
FOUNDATION_EXPORT const int64_t LibtechConnectionStateAll;
FOUNDATION_EXPORT const int64_t LibtechConnectionStateClosed;
FOUNDATION_EXPORT const int32_t LibtechInterfaceTypeCellular;
FOUNDATION_EXPORT const int32_t LibtechInterfaceTypeEthernet;
FOUNDATION_EXPORT const int32_t LibtechInterfaceTypeOther;
FOUNDATION_EXPORT const int32_t LibtechInterfaceTypeWIFI;
FOUNDATION_EXPORT const int64_t LibtechMessageTypeError;
FOUNDATION_EXPORT const int64_t LibtechMessageTypeProfileContent;
FOUNDATION_EXPORT const int64_t LibtechMessageTypeProfileContentRequest;
FOUNDATION_EXPORT const int64_t LibtechMessageTypeProfileList;
FOUNDATION_EXPORT const int32_t LibtechProfileTypeLocal;
FOUNDATION_EXPORT const int32_t LibtechProfileTypeRemote;
FOUNDATION_EXPORT const int32_t LibtechProfileTypeiCloud;

FOUNDATION_EXPORT BOOL LibtechCheckConfig(NSString* _Nullable configContent, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void LibtechClearServiceError(void);

FOUNDATION_EXPORT NSString* _Nonnull LibtechCommandServerPort(void);

FOUNDATION_EXPORT LibtechErrorMessage* _Nullable LibtechDecodeErrorMessage(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT int32_t LibtechDecodeLengthChunk(NSData* _Nullable data);

FOUNDATION_EXPORT LibtechProfileContent* _Nullable LibtechDecodeProfileContent(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT LibtechProfileContentRequest* _Nullable LibtechDecodeProfileContentRequest(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSData* _Nullable LibtechEncodeChunkedMessage(NSData* _Nullable data);

FOUNDATION_EXPORT NSString* _Nonnull LibtechFormatBytes(int64_t length);

FOUNDATION_EXPORT LibtechStringBox* _Nullable LibtechFormatConfig(NSString* _Nullable configContent, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull LibtechFormatDuration(int64_t duration);

FOUNDATION_EXPORT NSString* _Nonnull LibtechFormatMemoryBytes(int64_t length);

FOUNDATION_EXPORT NSString* _Nonnull LibtechGenerateRemoteProfileImportLink(NSString* _Nullable name, NSString* _Nullable remoteURL);

FOUNDATION_EXPORT int32_t LibtechGetTunnelFileDescriptor(void);

FOUNDATION_EXPORT LibtechCommandClient* _Nullable LibtechNewCommandClient(id<LibtechCommandClientHandler> _Nullable handler, LibtechCommandClientOptions* _Nullable options);

FOUNDATION_EXPORT LibtechCommandServer* _Nullable LibtechNewCommandServer(id<LibtechCommandServerHandler> _Nullable handler, int32_t maxLines);

FOUNDATION_EXPORT id<LibtechHTTPClient> _Nullable LibtechNewHTTPClient(void);

FOUNDATION_EXPORT LibtechPProfServer* _Nullable LibtechNewPProfServer(long port);

FOUNDATION_EXPORT LibtechBoxService* _Nullable LibtechNewService(NSString* _Nullable configContent, id<LibtechPlatformInterface> _Nullable platformInterface, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT LibtechCommandClient* _Nullable LibtechNewStandaloneCommandClient(void);

FOUNDATION_EXPORT LibtechWIFIState* _Nullable LibtechNewWIFIState(NSString* _Nullable wifiSSID, NSString* _Nullable wifiBSSID);

FOUNDATION_EXPORT NSString* _Nonnull LibtechParse(NSString* _Nullable uri);

FOUNDATION_EXPORT LibtechImportRemoteProfile* _Nullable LibtechParseRemoteProfileImportLink(NSString* _Nullable importLink, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull LibtechProxyDisplayType(NSString* _Nullable proxyType);

FOUNDATION_EXPORT LibtechStringBox* _Nullable LibtechReadServiceError(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL LibtechRedirectStderr(NSString* _Nullable path, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void LibtechRegisterLocalDNSTransport(id<LibtechLocalDNSTransport> _Nullable transport);

FOUNDATION_EXPORT void LibtechSetLocale(NSString* _Nullable localeId);

FOUNDATION_EXPORT void LibtechSetMemoryLimit(BOOL enabled);

FOUNDATION_EXPORT BOOL LibtechSetup(LibtechSetupOptions* _Nullable options, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull LibtechVersion(void);

FOUNDATION_EXPORT BOOL LibtechWriteServiceError(NSString* _Nullable message, NSError* _Nullable* _Nullable error);

@class LibtechCommandClientHandler;

@class LibtechCommandServerHandler;

@class LibtechConnectionIterator;

@class LibtechDeprecatedNoteIterator;

@class LibtechFunc;

@class LibtechHTTPClient;

@class LibtechHTTPRequest;

@class LibtechHTTPResponse;

@class LibtechInterfaceUpdateListener;

@class LibtechLocalDNSTransport;

@class LibtechNetworkInterfaceIterator;

@class LibtechOnDemandRule;

@class LibtechOnDemandRuleIterator;

@class LibtechOutboundGroupItemIterator;

@class LibtechOutboundGroupIterator;

@class LibtechPlatformInterface;

@class LibtechProfilePreviewIterator;

@class LibtechRoutePrefixIterator;

@class LibtechStringIterator;

@class LibtechTunInterface;

@class LibtechTunOptions;

@interface LibtechCommandClientHandler : NSObject <goSeqRefInterface, LibtechCommandClientHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)clearLogs;
- (void)connected;
- (void)disconnected:(NSString* _Nullable)message;
- (void)initializeClashMode:(id<LibtechStringIterator> _Nullable)modeList currentMode:(NSString* _Nullable)currentMode;
- (void)updateClashMode:(NSString* _Nullable)newMode;
- (void)writeConnections:(LibtechConnections* _Nullable)message;
- (void)writeGroups:(id<LibtechOutboundGroupIterator> _Nullable)message;
- (void)writeLogs:(id<LibtechStringIterator> _Nullable)messageList;
- (void)writeStatus:(LibtechStatusMessage* _Nullable)message;
@end

@interface LibtechCommandServerHandler : NSObject <goSeqRefInterface, LibtechCommandServerHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (LibtechSystemProxyStatus* _Nullable)getSystemProxyStatus;
- (void)postServiceClose;
- (BOOL)serviceReload:(NSError* _Nullable* _Nullable)error;
- (BOOL)setSystemProxyEnabled:(BOOL)isEnabled error:(NSError* _Nullable* _Nullable)error;
@end

@interface LibtechConnectionIterator : NSObject <goSeqRefInterface, LibtechConnectionIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibtechConnection* _Nullable)next;
@end

@interface LibtechDeprecatedNoteIterator : NSObject <goSeqRefInterface, LibtechDeprecatedNoteIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibtechDeprecatedNote* _Nullable)next;
@end

@interface LibtechFunc : NSObject <goSeqRefInterface, LibtechFunc> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)invoke:(NSError* _Nullable* _Nullable)error;
@end

@interface LibtechHTTPClient : NSObject <goSeqRefInterface, LibtechHTTPClient> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)close;
- (void)keepAlive;
- (void)modernTLS;
- (id<LibtechHTTPRequest> _Nullable)newRequest;
- (void)pinnedSHA256:(NSString* _Nullable)sumHex;
- (void)pinnedTLS12;
- (void)restrictedTLS;
- (void)trySocks5:(int32_t)port;
@end

@interface LibtechHTTPRequest : NSObject <goSeqRefInterface, LibtechHTTPRequest> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (id<LibtechHTTPResponse> _Nullable)execute:(NSError* _Nullable* _Nullable)error;
- (void)randomUserAgent;
- (void)setContent:(NSData* _Nullable)content;
- (void)setContentString:(NSString* _Nullable)content;
- (void)setHeader:(NSString* _Nullable)key value:(NSString* _Nullable)value;
- (void)setMethod:(NSString* _Nullable)method;
- (BOOL)setURL:(NSString* _Nullable)link error:(NSError* _Nullable* _Nullable)error;
- (void)setUserAgent:(NSString* _Nullable)userAgent;
@end

@interface LibtechHTTPResponse : NSObject <goSeqRefInterface, LibtechHTTPResponse> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (LibtechStringBox* _Nullable)getContent:(NSError* _Nullable* _Nullable)error;
- (BOOL)writeTo:(NSString* _Nullable)path error:(NSError* _Nullable* _Nullable)error;
@end

@interface LibtechInterfaceUpdateListener : NSObject <goSeqRefInterface, LibtechInterfaceUpdateListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)updateDefaultInterface:(NSString* _Nullable)interfaceName interfaceIndex:(int32_t)interfaceIndex isExpensive:(BOOL)isExpensive isConstrained:(BOOL)isConstrained;
@end

@interface LibtechLocalDNSTransport : NSObject <goSeqRefInterface, LibtechLocalDNSTransport> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)exchange:(LibtechExchangeContext* _Nullable)ctx message:(NSData* _Nullable)message error:(NSError* _Nullable* _Nullable)error;
- (BOOL)lookup:(LibtechExchangeContext* _Nullable)ctx network:(NSString* _Nullable)network domain:(NSString* _Nullable)domain error:(NSError* _Nullable* _Nullable)error;
- (BOOL)raw;
@end

@interface LibtechNetworkInterfaceIterator : NSObject <goSeqRefInterface, LibtechNetworkInterfaceIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibtechNetworkInterface* _Nullable)next;
@end

@interface LibtechOnDemandRule : NSObject <goSeqRefInterface, LibtechOnDemandRule> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (id<LibtechStringIterator> _Nullable)dnsSearchDomainMatch;
- (id<LibtechStringIterator> _Nullable)dnsServerAddressMatch;
- (int32_t)interfaceTypeMatch;
- (NSString* _Nonnull)probeURL;
- (id<LibtechStringIterator> _Nullable)ssidMatch;
- (int32_t)target;
@end

@interface LibtechOnDemandRuleIterator : NSObject <goSeqRefInterface, LibtechOnDemandRuleIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (id<LibtechOnDemandRule> _Nullable)next;
@end

@interface LibtechOutboundGroupItemIterator : NSObject <goSeqRefInterface, LibtechOutboundGroupItemIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibtechOutboundGroupItem* _Nullable)next;
@end

@interface LibtechOutboundGroupIterator : NSObject <goSeqRefInterface, LibtechOutboundGroupIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibtechOutboundGroup* _Nullable)next;
@end

@interface LibtechPlatformInterface : NSObject <goSeqRefInterface, LibtechPlatformInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)autoDetectInterfaceControl:(int32_t)fd error:(NSError* _Nullable* _Nullable)error;
- (void)clearDNSCache;
- (BOOL)closeDefaultInterfaceMonitor:(id<LibtechInterfaceUpdateListener> _Nullable)listener error:(NSError* _Nullable* _Nullable)error;
- (BOOL)findConnectionOwner:(int32_t)ipProtocol sourceAddress:(NSString* _Nullable)sourceAddress sourcePort:(int32_t)sourcePort destinationAddress:(NSString* _Nullable)destinationAddress destinationPort:(int32_t)destinationPort ret0_:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (id<LibtechNetworkInterfaceIterator> _Nullable)getInterfaces:(NSError* _Nullable* _Nullable)error;
- (BOOL)includeAllNetworks;
- (BOOL)openTun:(id<LibtechTunOptions> _Nullable)options ret0_:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)packageNameByUid:(int32_t)uid error:(NSError* _Nullable* _Nullable)error;
- (LibtechWIFIState* _Nullable)readWIFIState;
- (BOOL)sendNotification:(LibtechNotification* _Nullable)notification error:(NSError* _Nullable* _Nullable)error;
- (BOOL)startDefaultInterfaceMonitor:(id<LibtechInterfaceUpdateListener> _Nullable)listener error:(NSError* _Nullable* _Nullable)error;
- (BOOL)uidByPackageName:(NSString* _Nullable)packageName ret0_:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (BOOL)underNetworkExtension;
- (BOOL)usePlatformAutoDetectInterfaceControl;
- (BOOL)useProcFS;
- (void)writeLog:(NSString* _Nullable)message;
@end

@interface LibtechProfilePreviewIterator : NSObject <goSeqRefInterface, LibtechProfilePreviewIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibtechProfilePreview* _Nullable)next;
@end

@interface LibtechRoutePrefixIterator : NSObject <goSeqRefInterface, LibtechRoutePrefixIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibtechRoutePrefix* _Nullable)next;
@end

@interface LibtechStringIterator : NSObject <goSeqRefInterface, LibtechStringIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (int32_t)len;
- (NSString* _Nonnull)next;
@end

@interface LibtechTunInterface : NSObject <goSeqRefInterface, LibtechTunInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (int32_t)fileDescriptor;
@end

@interface LibtechTunOptions : NSObject <goSeqRefInterface, LibtechTunOptions> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)getAutoRoute;
- (LibtechStringBox* _Nullable)getDNSServerAddress:(NSError* _Nullable* _Nullable)error;
- (id<LibtechStringIterator> _Nullable)getExcludePackage;
- (id<LibtechStringIterator> _Nullable)getHTTPProxyBypassDomain;
- (id<LibtechStringIterator> _Nullable)getHTTPProxyMatchDomain;
- (NSString* _Nonnull)getHTTPProxyServer;
- (int32_t)getHTTPProxyServerPort;
- (id<LibtechStringIterator> _Nullable)getIncludePackage;
- (id<LibtechRoutePrefixIterator> _Nullable)getInet4Address;
- (id<LibtechRoutePrefixIterator> _Nullable)getInet4RouteAddress;
- (id<LibtechRoutePrefixIterator> _Nullable)getInet4RouteExcludeAddress;
- (id<LibtechRoutePrefixIterator> _Nullable)getInet4RouteRange;
- (id<LibtechRoutePrefixIterator> _Nullable)getInet6Address;
- (id<LibtechRoutePrefixIterator> _Nullable)getInet6RouteAddress;
- (id<LibtechRoutePrefixIterator> _Nullable)getInet6RouteExcludeAddress;
- (id<LibtechRoutePrefixIterator> _Nullable)getInet6RouteRange;
- (int32_t)getMTU;
- (BOOL)getStrictRoute;
- (BOOL)isHTTPProxyEnabled;
@end

#endif
