
// Objective-C API for talking to the following Go packages
//
//	github.com/sagernet/sing-box/experimental/libtech
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Libtech_FRAMEWORK_H__
#define __Libtech_FRAMEWORK_H__

#include "Libtech.objc.h"
#include "Universe.objc.h"

#endif
